[project]
name = "farmdb"
version = "0.1.2"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.4.3",
    "fastapi[standard]>=0.128.0",
    "pydantic-settings>=2.12.0",
    "typer>=0.9.0",
    "uvicorn>=0.40.0",
]

[project.scripts]
farmdb = "cli:app"

[tool.uv]
package = true

[tool.setuptools]
package-dir = {"" = "src"}

[tool.semantic_release]
version_variable = "pyproject.toml:project.version"
branch = "master"
upload_to_pypi = false
build_command = ""
changelog_file = "CHANGELOG.md"

[tool.semantic_release.commit_parser_options]
allowed_tags = ["feat", "fix", "chore","refactor"] 
minor_tags = ["feat", "chore", "refactor"]           
patch_tags = ["fix"]
